
---
route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
- name: 'telegram'
  telegram_configs:
  - api_url: 'https://api.telegram.org'
    bot_token: '7781749823:AAFcScZry074qYBnU5khGqT5hKukJ-glHSQ' # Замените на реальный токен
    chat_id: -1002521706671          # Замените на реальный chat ID
    message: |-
      {{ range .Alerts -}}
      [{{ .Status }}] {{ .Labels.severity | upper }}: {{ .Annotations.summary }}
      Instance: {{ .Labels.instance }}
      {{ .Annotations.description }}
      {{ end }}
    send_resolved: true
